/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Novella.YMain;

import Novella.Database.DatabaseManager.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Koka
 */
public class AddNewBookJframe extends javax.swing.JFrame {

    /**
     * Creates new form AddNewBookJframe
     */
    public AddNewBookJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jISBN = new javax.swing.JTextField();
        jTitle = new javax.swing.JTextField();
        jDDC = new javax.swing.JTextField();
        jPublisher = new javax.swing.JTextField();
        jSubject = new javax.swing.JTextField();
        jAuthor = new javax.swing.JTextField();
        jPages = new javax.swing.JTextField();
        jYear = new javax.swing.JTextField();
        jLocation = new javax.swing.JTextField();
        jBookNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add New Book");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book DDC:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Book ISBN:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book Title:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Publisher:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Subject:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Author:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Year:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pages:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Amount of Copies Availiable:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Book Number:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jISBN.setBackground(new java.awt.Color(255, 255, 255));
        jISBN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jISBN.setForeground(new java.awt.Color(0, 0, 0));
        jISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 204, -1));

        jTitle.setBackground(new java.awt.Color(255, 255, 255));
        jTitle.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTitle.setForeground(new java.awt.Color(0, 0, 0));
        jTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 204, -1));

        jDDC.setBackground(new java.awt.Color(255, 255, 255));
        jDDC.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jDDC.setForeground(new java.awt.Color(0, 0, 0));
        jDDC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jDDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 204, -1));

        jPublisher.setBackground(new java.awt.Color(255, 255, 255));
        jPublisher.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPublisher.setForeground(new java.awt.Color(0, 0, 0));
        jPublisher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 204, -1));

        jSubject.setBackground(new java.awt.Color(255, 255, 255));
        jSubject.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jSubject.setForeground(new java.awt.Color(0, 0, 0));
        jSubject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 204, -1));

        jAuthor.setBackground(new java.awt.Color(255, 255, 255));
        jAuthor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jAuthor.setForeground(new java.awt.Color(0, 0, 0));
        jAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 204, -1));

        jPages.setBackground(new java.awt.Color(255, 255, 255));
        jPages.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPages.setForeground(new java.awt.Color(0, 0, 0));
        jPages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 94, -1));

        jYear.setBackground(new java.awt.Color(255, 255, 255));
        jYear.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jYear.setForeground(new java.awt.Color(0, 0, 0));
        jYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 94, -1));

        jLocation.setBackground(new java.awt.Color(255, 255, 255));
        jLocation.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLocation.setForeground(new java.awt.Color(0, 0, 0));
        jLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 94, -1));

        jBookNumber.setBackground(new java.awt.Color(255, 255, 255));
        jBookNumber.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBookNumber.setForeground(new java.awt.Color(0, 0, 0));
        jBookNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jBookNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 187, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 60, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Save & Add New");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 110, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Novella/YMain/Images/ISSUE BOOK PAGE.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 560));

        setSize(new java.awt.Dimension(369, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String ISBN = jISBN.getText();
        String Title = jTitle.getText();
        String DDC = jDDC.getText();
        String Publisher = jPublisher.getText();
        String Subject = jSubject.getText();
        //String Date = jDate.getDateFormatString();
        String Author = jAuthor.getText();
        //String Edition = jEdition.getText();
        //String Vol = jVol.getText();
        String Year = jYear.getText();
        String Pages = jPages.getText();
        String BookAvlAmount = jLocation.getText();
        String BookNumber = jBookNumber.getText();
        
        MainView b = new MainView();

        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st1 = con.createStatement();
            st1.executeUpdate("insert into books values('"+ISBN+"','"+Title+"','"+DDC+"','"+Publisher+"','"+Subject+"','"+Author+"','"+Year+"','"+Pages+"','"+BookAvlAmount+"','"+BookNumber+"')");
            JOptionPane.showMessageDialog(null,"Succesfully Updated");
            this.dispose();
            b.setVisible(true);
            

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            this.dispose();
            new MainView().setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new MainView().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String ISBN = jISBN.getText();
        String Title = jTitle.getText();
        String DDC = jDDC.getText();
        String Publisher = jPublisher.getText();
        String Subject = jSubject.getText();
        String Author = jAuthor.getText();
        String Year = jYear.getText();
        String Pages = jPages.getText();
        String BookAvlAmount = jLocation.getText();
        String BookNumber = jBookNumber.getText();
        
        MainView b = new MainView();

        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st1 = con.createStatement();
            st1.executeUpdate("insert into books values('"+ISBN+"','"+Title+"','"+DDC+"','"+Publisher+"','"+Subject+"','"+Author+"','"+Year+"','"+Pages+"','"+BookAvlAmount+"','"+BookNumber+"')");
            JOptionPane.showMessageDialog(null,"Succesfully Updated");
            
            
            this.dispose();
            new AddNewBookJframe().setVisible(true);
            

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            this.dispose();
            new MainView().setVisible(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewBookJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewBookJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewBookJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewBookJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewBookJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAuthor;
    private javax.swing.JTextField jBookNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jDDC;
    private javax.swing.JTextField jISBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLocation;
    private javax.swing.JTextField jPages;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPublisher;
    private javax.swing.JTextField jSubject;
    private javax.swing.JTextField jTitle;
    private javax.swing.JTextField jYear;
    // End of variables declaration//GEN-END:variables
}
