/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Novella.YMain;

//import Novella.JFrames.*;

//import java.awt.event.ActionListener;
import Novella.Database.DatabaseManager.ConnectionProvider;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Koka
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hidebar1 = new javax.swing.JPanel();
        Hidebar3 = new javax.swing.JPanel();
        Hidebar4 = new javax.swing.JPanel();
        Hidebar2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        IssueBookjPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IndexSearchField = new javax.swing.JTextField();
        StudentGradeget = new javax.swing.JTextField();
        StudentNameget = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ISBNSearchField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        BookTitleget = new javax.swing.JTextField();
        BookAuthorget = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        issueBookDateget = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        RecievejPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        returnISBNget = new javax.swing.JTextField();
        returnIndexget = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        returnBookget = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        returnAuthorget = new javax.swing.JTextField();
        returnGradeget = new javax.swing.JTextField();
        returnNameget = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        returnDateget = new com.toedter.calendar.JDateChooser();
        Statistics = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BookDirectory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        StudentTables = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        EmptyPane1 = new javax.swing.JPanel();
        StudentDashboard = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UnreturnedBooksLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        StudentDashboardLabel = new javax.swing.JLabel();
        IssueBook3 = new javax.swing.JLabel();
        IssueBook2 = new javax.swing.JLabel();
        IssueBook1 = new javax.swing.JLabel();
        AddNewBook = new javax.swing.JLabel();
        NumberOfBooksjLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StudentTablesLabel = new javax.swing.JLabel();
        NumberOfStudentjLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hidebar1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar1Layout = new javax.swing.GroupLayout(Hidebar1);
        Hidebar1.setLayout(Hidebar1Layout);
        Hidebar1Layout.setHorizontalGroup(
            Hidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Hidebar1Layout.setVerticalGroup(
            Hidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 20, 450));

        Hidebar3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar3Layout = new javax.swing.GroupLayout(Hidebar3);
        Hidebar3.setLayout(Hidebar3Layout);
        Hidebar3Layout.setHorizontalGroup(
            Hidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        Hidebar3Layout.setVerticalGroup(
            Hidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 870, 30));

        Hidebar4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar4Layout = new javax.swing.GroupLayout(Hidebar4);
        Hidebar4.setLayout(Hidebar4Layout);
        Hidebar4Layout.setHorizontalGroup(
            Hidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        Hidebar4Layout.setVerticalGroup(
            Hidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 860, 20));

        Hidebar2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar2Layout = new javax.swing.GroupLayout(Hidebar2);
        Hidebar2.setLayout(Hidebar2Layout);
        Hidebar2Layout.setHorizontalGroup(
            Hidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Hidebar2Layout.setVerticalGroup(
            Hidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 20, 450));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        IssueBookjPanel.setBackground(new java.awt.Color(255, 255, 255));
        IssueBookjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Issue Books to Students");
        IssueBookjPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Student Index:");
        IssueBookjPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Issue Date:");
        IssueBookjPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 30));

        IndexSearchField.setBackground(new java.awt.Color(255, 255, 255));
        IndexSearchField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        IndexSearchField.setForeground(new java.awt.Color(0, 0, 0));
        IndexSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexSearchFieldActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(IndexSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 104, 150, -1));

        StudentGradeget.setBackground(new java.awt.Color(255, 255, 255));
        StudentGradeget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        StudentGradeget.setForeground(new java.awt.Color(0, 0, 0));
        StudentGradeget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentGradegetActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(StudentGradeget, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, -1));

        StudentNameget.setBackground(new java.awt.Color(255, 255, 255));
        StudentNameget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        StudentNameget.setForeground(new java.awt.Color(0, 0, 0));
        StudentNameget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNamegetActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(StudentNameget, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Student Name:");
        IssueBookjPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        IssueBookjPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 20, 160));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton5.setText("Issue Book");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        IssueBookjPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton3.setText("Search");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        IssueBookjPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Book ISBN:");
        IssueBookjPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, 20));

        ISBNSearchField.setBackground(new java.awt.Color(255, 255, 255));
        ISBNSearchField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ISBNSearchField.setForeground(new java.awt.Color(0, 0, 0));
        ISBNSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNSearchFieldActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(ISBNSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 150, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton4.setText("Search");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        IssueBookjPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        BookTitleget.setBackground(new java.awt.Color(255, 255, 255));
        BookTitleget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BookTitleget.setForeground(new java.awt.Color(0, 0, 0));
        BookTitleget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTitlegetActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(BookTitleget, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 230, -1));

        BookAuthorget.setBackground(new java.awt.Color(255, 255, 255));
        BookAuthorget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BookAuthorget.setForeground(new java.awt.Color(0, 0, 0));
        BookAuthorget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAuthorgetActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(BookAuthorget, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 230, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Book Author:");
        IssueBookjPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Book Title:");
        IssueBookjPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Book Details");
        IssueBookjPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, 20));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Student Details");
        IssueBookjPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 53, -1, 20));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("I would like to send a message to the student's phone number about the book?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        IssueBookjPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        issueBookDateget.setBackground(new java.awt.Color(255, 255, 255));
        issueBookDateget.setForeground(new java.awt.Color(0, 0, 0));
        IssueBookjPanel.add(issueBookDateget, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 140, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Student Grade:");
        IssueBookjPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jTabbedPane1.addTab("tab1", IssueBookjPanel);

        RecievejPanel.setBackground(new java.awt.Color(255, 255, 255));
        RecievejPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Recieve Book");
        RecievejPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jTable5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.setGridColor(new java.awt.Color(0, 0, 0));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jTable5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable5KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        RecievejPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 790, 80));

        returnISBNget.setBackground(new java.awt.Color(255, 255, 255));
        returnISBNget.setForeground(new java.awt.Color(0, 0, 0));
        RecievejPanel.add(returnISBNget, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 220, 30));

        returnIndexget.setBackground(new java.awt.Color(255, 255, 255));
        returnIndexget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        returnIndexget.setForeground(new java.awt.Color(0, 0, 0));
        RecievejPanel.add(returnIndexget, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Search");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        RecievejPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 70, 30));

        returnBookget.setBackground(new java.awt.Color(255, 255, 255));
        returnBookget.setForeground(new java.awt.Color(0, 0, 0));
        RecievejPanel.add(returnBookget, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 220, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Return Book");
        RecievejPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Seach by index:");
        RecievejPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 30));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Book ISBN:");
        RecievejPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Book Author:");
        RecievejPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, 30));

        returnAuthorget.setBackground(new java.awt.Color(255, 255, 255));
        returnAuthorget.setForeground(new java.awt.Color(0, 0, 0));
        RecievejPanel.add(returnAuthorget, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 220, 30));

        returnGradeget.setBackground(new java.awt.Color(255, 255, 255));
        returnGradeget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        returnGradeget.setForeground(new java.awt.Color(0, 0, 0));
        RecievejPanel.add(returnGradeget, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, 30));

        returnNameget.setBackground(new java.awt.Color(255, 255, 255));
        returnNameget.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        returnNameget.setForeground(new java.awt.Color(0, 0, 0));
        RecievejPanel.add(returnNameget, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 210, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Return Book");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        RecievejPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 110, 40));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Student Name:");
        RecievejPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Book Title:");
        RecievejPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, 30));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Student Grade:");
        RecievejPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Student Grade:");
        RecievejPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 30));
        RecievejPanel.add(returnDateget, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 210, -1));

        jTabbedPane1.addTab("tab2", RecievejPanel);

        Statistics.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Issued Books");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Returned Books");

        javax.swing.GroupLayout StatisticsLayout = new javax.swing.GroupLayout(Statistics);
        Statistics.setLayout(StatisticsLayout);
        StatisticsLayout.setHorizontalGroup(
            StatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsLayout.createSequentialGroup()
                .addGroup(StatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatisticsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(StatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(StatisticsLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel22))
                    .addGroup(StatisticsLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel10)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        StatisticsLayout.setVerticalGroup(
            StatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", Statistics);

        BookDirectory.setBackground(new java.awt.Color(255, 255, 255));
        BookDirectory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable2ComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        BookDirectory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 830, 360));

        jButton2.setText("Add New Book");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        BookDirectory.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jTabbedPane1.addTab("tab5", BookDirectory);

        StudentTables.setBackground(new java.awt.Color(255, 255, 255));
        StudentTables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        StudentTables.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 360));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setText("Add New Student");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        StudentTables.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jTabbedPane1.addTab("tab6", StudentTables);

        EmptyPane1.setBackground(new java.awt.Color(255, 255, 255));
        EmptyPane1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyPane1Layout = new javax.swing.GroupLayout(EmptyPane1);
        EmptyPane1.setLayout(EmptyPane1Layout);
        EmptyPane1Layout.setHorizontalGroup(
            EmptyPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        EmptyPane1Layout.setVerticalGroup(
            EmptyPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", EmptyPane1);

        StudentDashboard.setBackground(new java.awt.Color(255, 255, 255));
        StudentDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Unreturned Books");
        StudentDashboard.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Novella/YMain/Images/Pie Chart.png"))); // NOI18N
        StudentDashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("of Students to Staff in R.A.E.C");
        StudentDashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Pie Chart Representation");
        StudentDashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        UnreturnedBooksLabel.setBackground(new java.awt.Color(255, 255, 255));
        UnreturnedBooksLabel.setFont(new java.awt.Font("Century Gothic", 0, 40)); // NOI18N
        UnreturnedBooksLabel.setForeground(new java.awt.Color(255, 255, 255));
        UnreturnedBooksLabel.setText("00");
        StudentDashboard.add(UnreturnedBooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 50, 50, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Novella/YMain/Images/Circles.png"))); // NOI18N
        StudentDashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTabbedPane1.addTab("tab3", StudentDashboard);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 850, 470));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 10));

        StudentDashboardLabel.setBackground(new java.awt.Color(255, 255, 255));
        StudentDashboardLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentDashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        StudentDashboardLabel.setText("Student Dashboard");
        StudentDashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentDashboardLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudentDashboardLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudentDashboardLabelMouseExited(evt);
            }
        });
        getContentPane().add(StudentDashboardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        IssueBook3.setBackground(new java.awt.Color(255, 255, 255));
        IssueBook3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        IssueBook3.setForeground(new java.awt.Color(255, 255, 255));
        IssueBook3.setText("Recieve Book");
        IssueBook3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueBook3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IssueBook3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IssueBook3MouseExited(evt);
            }
        });
        getContentPane().add(IssueBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        IssueBook2.setBackground(new java.awt.Color(255, 255, 255));
        IssueBook2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        IssueBook2.setForeground(new java.awt.Color(255, 255, 255));
        IssueBook2.setText("Statistics");
        IssueBook2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueBook2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IssueBook2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IssueBook2MouseExited(evt);
            }
        });
        getContentPane().add(IssueBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        IssueBook1.setBackground(new java.awt.Color(255, 255, 255));
        IssueBook1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        IssueBook1.setForeground(new java.awt.Color(255, 255, 255));
        IssueBook1.setText("Issue Book");
        IssueBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueBook1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IssueBook1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IssueBook1MouseExited(evt);
            }
        });
        getContentPane().add(IssueBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        AddNewBook.setBackground(new java.awt.Color(255, 255, 255));
        AddNewBook.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AddNewBook.setForeground(new java.awt.Color(255, 255, 255));
        AddNewBook.setText("Book Directory");
        AddNewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddNewBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddNewBookMouseExited(evt);
            }
        });
        getContentPane().add(AddNewBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        NumberOfBooksjLabel.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        NumberOfBooksjLabel.setForeground(new java.awt.Color(255, 255, 255));
        NumberOfBooksjLabel.setText("000");
        getContentPane().add(NumberOfBooksjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, -1, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of Books Availiable");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number of Students");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, -1, 20));

        StudentTablesLabel.setBackground(new java.awt.Color(255, 255, 255));
        StudentTablesLabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        StudentTablesLabel.setForeground(new java.awt.Color(255, 255, 255));
        StudentTablesLabel.setText("Student Directory");
        StudentTablesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTablesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudentTablesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudentTablesLabelMouseExited(evt);
            }
        });
        getContentPane().add(StudentTablesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        NumberOfStudentjLabel.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        NumberOfStudentjLabel.setForeground(new java.awt.Color(255, 255, 255));
        NumberOfStudentjLabel.setText("000");
        getContentPane().add(NumberOfStudentjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Novella/YMain/Images/HOME 22.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 600));

        setSize(new java.awt.Dimension(1149, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StudentDashboardLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDashboardLabelMouseEntered
        // TODO add your handling code here:
        StudentDashboardLabel.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_StudentDashboardLabelMouseEntered

    private void StudentDashboardLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDashboardLabelMouseExited
        // TODO add your handling code here:
        StudentDashboardLabel.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_StudentDashboardLabelMouseExited

    private void IssueBook1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook1MouseEntered
        // TODO add your handling code here:
        IssueBook1.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_IssueBook1MouseEntered

    private void IssueBook1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook1MouseExited
        // TODO add your handling code here:
        IssueBook1.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_IssueBook1MouseExited

    private void AddNewBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewBookMouseEntered
        // TODO add your handling code here:
        AddNewBook.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_AddNewBookMouseEntered

    private void AddNewBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewBookMouseExited
        // TODO add your handling code here:
        AddNewBook.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_AddNewBookMouseExited

    private void AddNewBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewBookMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(BookDirectory);
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs9 = st.executeQuery("SELECT books.ISBN,books.Title,books.DDC,books.Publisher,books.Subject,books.Author,books.Year,books.Pages,books.BookAvlAmount,books.BookNumber from books");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs9));
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                
    }//GEN-LAST:event_AddNewBookMouseClicked

    private void StudentDashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDashboardLabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(StudentDashboard);
    }//GEN-LAST:event_StudentDashboardLabelMouseClicked

    private void IssueBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(IssueBookjPanel);
    }//GEN-LAST:event_IssueBook1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        AddNewStudentJframe a = new AddNewStudentJframe();
        setVisible(false);
        a.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        AddNewBookJframe m = new AddNewBookJframe();
        m.setVisible(true);
       
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTable2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentShown
        // TODO add your handling code here:
        setVisible(true);
    }//GEN-LAST:event_jTable2ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT student.studentIndex,student.studentName,student.studentClass,student.studentAddress,student.studentIsland,student.studentPhone from student");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            ResultSet rsl = st.executeQuery("SELECT books.ISBN,books.Title,books.DDC,books.Publisher,books.Subject,books.Author,books.Year,books.Pages,books.BookAvlAmount,books.BookNumber from books");
            jTable2.setModel(DbUtils.resultSetToTableModel(rsl));
            ResultSet rs5 = st.executeQuery("select issue.issueIndex,issue.issueName,issue.issueGrade,issue.issueISBN,issue.issueTitle,issue.issueAuthor,issue.issueDate from issue");
            jTable3.setModel(DbUtils.resultSetToTableModel(rs5));
            ResultSet rs9 = st.executeQuery("select bookrs.bookrsIndex,bookrs.bookrsName,bookrs.bookrsGrade,bookrs.bookrsISBN,bookrs.bookrsTitle,bookrs.bookrsAuthor,bookrs.bookrsDate from bookrs");
            jTable4.setModel(DbUtils.resultSetToTableModel(rs9));
            
            
            String query = "select count(*) from books";
            ResultSet rs2 = st.executeQuery(query);
            //Refreshing Number of Books Label
            if (rs2.next())
            {
                String p = rs2.getString(1);
                
                String quer = "select count(*) from student";
                ResultSet rs3 = st.executeQuery(quer);
                NumberOfBooksjLabel.setText(p);
                
                if (rs3.next())
                {
                    String q = rs3.getString(1);
                    NumberOfStudentjLabel.setText(q);
                    
                    String queri = "select count(*) from issue";
                    ResultSet rs4 = st.executeQuery(queri);
                    
                    if (rs4.next())
                    {
                        int count;
                        count = rs4.getInt(1);
                        
                        String county = rs4.getString(1);
                       
                        if(count < 9)
                        {
                            UnreturnedBooksLabel.setText(0+county);
                        }
                        else
                        {
                            UnreturnedBooksLabel.setText(county);
                        }
                        
                        
                        
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Failed to retrieve Number of Students");
                }
                 
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Failed to retrieve Number of Books");
                
                new MainView().setVisible(true);
            } 
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    
    }//GEN-LAST:event_formComponentShown

    private void StudentTablesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTablesLabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(StudentTables);
    }//GEN-LAST:event_StudentTablesLabelMouseClicked

    private void StudentTablesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTablesLabelMouseEntered
        // TODO add your handling code here:
        StudentTablesLabel.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_StudentTablesLabelMouseEntered

    private void StudentTablesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTablesLabelMouseExited
        // TODO add your handling code here:
        StudentTablesLabel.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_StudentTablesLabelMouseExited

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentAdded

    private void IndexSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexSearchFieldActionPerformed
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_IndexSearchFieldActionPerformed

    private void StudentGradegetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentGradegetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentGradegetActionPerformed

    private void StudentNamegetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNamegetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNamegetActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String INDEXSearch = IndexSearchField.getText();
        
        try 
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select *from student where studentIndex='"+INDEXSearch+"'");
            if (rs.next())
            {
                StudentNameget.setText(rs.getString(2));
                StudentGradeget.setText(rs.getString(5));
                   
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Failed to retrieve student Index form Database");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e );
            this.dispose();
            new MainView().setVisible(true);
        } 
    }//GEN-LAST:event_jButton3MouseClicked

    private void ISBNSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNSearchFieldActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String ISBNSearch = ISBNSearchField.getText();
        
        try 
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select *from books where ISBN='"+ISBNSearch+"'");
            if (rs.next())
            {
                BookTitleget.setText(rs.getString(2));
                BookAuthorget.setText(rs.getString(6));
                   
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Failed to retrieve book ISBN form Database");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e );
            this.dispose();
            new MainView().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void BookTitlegetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTitlegetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookTitlegetActionPerformed

    private void BookAuthorgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAuthorgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookAuthorgetActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        String issueIndex = IndexSearchField.getText();
        String issueName = StudentNameget.getText();
        String issueGrade = StudentGradeget.getText();
        String issueISBN = ISBNSearchField.getText();
        String issueTitle = BookTitleget.getText();
        String issueAuthor = BookAuthorget.getText();
        String issueDate = dFormat.format (issueBookDateget.getDate());
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from books where ISBN = '"+issueISBN+"'");
            if(rs.next())
                    {
                      
                      ResultSet rsl = st.executeQuery("select *from student where studentIndex = '"+issueIndex+"'"); 
                      if(rsl.next())
                      {
                          
                          st.executeUpdate("insert into issue values('"+issueIndex+"','"+issueName+"','"+issueGrade+"','"+issueISBN+"','"+issueTitle+"','"+issueAuthor+"','"+issueDate+"')");
                          
                          JOptionPane.showMessageDialog(null,"Succesfully Issued");
                          this.setVisible(false);
                          new MainView().setVisible(true);
                      }
                      else
                      JOptionPane.showConfirmDialog(null, "Incorrect Student Index");    
                    }
            else 
                JOptionPane.showConfirmDialog(null, "Incorrect Book ISBN Number");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
                
    }//GEN-LAST:event_jButton5MouseClicked

    private void IssueBook2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(Statistics);
    }//GEN-LAST:event_IssueBook2MouseClicked

    private void IssueBook2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook2MouseEntered
        // TODO add your handling code here:
        IssueBook2.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_IssueBook2MouseEntered

    private void IssueBook2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook2MouseExited
        // TODO add your handling code here:
        IssueBook2.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_IssueBook2MouseExited

    private void IssueBook3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(RecievejPanel);
    }//GEN-LAST:event_IssueBook3MouseClicked

    private void IssueBook3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_IssueBook3MouseEntered

    private void IssueBook3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_IssueBook3MouseExited

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String returnIndex = returnIndexget.getText();
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from issue where issueIndex='"+returnIndex+"'"); 
            if(rs.next())
            {
                ResultSet rs2 =st.executeQuery("select issue.issueIndex AS 'Student Index',issue.issueName AS 'Name',issue.issueGrade AS 'Grade',issue.issueISBN AS 'ISBN',issue.issueTitle AS 'Title',issue.issueAuthor AS 'Author',issue.issueDate AS 'Date Issued' from issue where issueIndex='"+returnIndex+"'");
                jTable5.setModel(DbUtils.resultSetToTableModel(rs2));
            }
            else
            {
                
            }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
                
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTable5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable5KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable5KeyPressed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable5.getModel();
        int selectedRowIndex = jTable5.getSelectedRow();
        
        returnNameget.setText(model.getValueAt(selectedRowIndex, 1).toString());
        returnGradeget.setText(model.getValueAt(selectedRowIndex, 2).toString());
        returnISBNget.setText(model.getValueAt(selectedRowIndex, 3).toString());
        returnBookget.setText(model.getValueAt(selectedRowIndex, 4).toString());
        returnAuthorget.setText(model.getValueAt(selectedRowIndex, 5).toString());
        
         
    }//GEN-LAST:event_jTable5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        
        String bookrsName = returnNameget.getText();
        String bookrsTitle = returnBookget.getText();
        String bookrsIndex = returnIndexget.getText();
        String bookrsGrade = returnGradeget.getText();
        String bookrsAuthor = returnAuthorget.getText();
        String bookrsISBN = returnISBNget.getText();
        String bookrsDate = dFormat.format (returnDateget.getDate());
        
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            Statement st2 = con.createStatement();
            
            st2.executeUpdate("insert into bookrs values('"+bookrsIndex+"','"+bookrsName+"','"+bookrsGrade+"','"+bookrsISBN+"','"+bookrsTitle+"','"+bookrsAuthor+"','"+bookrsDate+"')");
            
            st.executeUpdate("DELETE FROM issue where issueIndex='"+bookrsIndex+"' and issueTitle='"+bookrsTitle+"'");
            
            
            JOptionPane.showMessageDialog(null, "Succesfully Returned");
            this.setVisible(false);
            new MainView().setVisible(true);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewBook;
    private javax.swing.JTextField BookAuthorget;
    private javax.swing.JPanel BookDirectory;
    private javax.swing.JTextField BookTitleget;
    private javax.swing.JPanel EmptyPane1;
    private javax.swing.JPanel Hidebar1;
    private javax.swing.JPanel Hidebar2;
    private javax.swing.JPanel Hidebar3;
    private javax.swing.JPanel Hidebar4;
    private javax.swing.JTextField ISBNSearchField;
    private javax.swing.JTextField IndexSearchField;
    private javax.swing.JLabel IssueBook1;
    private javax.swing.JLabel IssueBook2;
    private javax.swing.JLabel IssueBook3;
    private javax.swing.JPanel IssueBookjPanel;
    public javax.swing.JLabel NumberOfBooksjLabel;
    public javax.swing.JLabel NumberOfStudentjLabel;
    private javax.swing.JPanel RecievejPanel;
    private javax.swing.JPanel Statistics;
    private javax.swing.JPanel StudentDashboard;
    private javax.swing.JLabel StudentDashboardLabel;
    private javax.swing.JTextField StudentGradeget;
    private javax.swing.JTextField StudentNameget;
    public javax.swing.JPanel StudentTables;
    private javax.swing.JLabel StudentTablesLabel;
    private javax.swing.JLabel UnreturnedBooksLabel;
    private com.toedter.calendar.JDateChooser issueBookDateget;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField returnAuthorget;
    private javax.swing.JTextField returnBookget;
    private com.toedter.calendar.JDateChooser returnDateget;
    private javax.swing.JTextField returnGradeget;
    private javax.swing.JTextField returnISBNget;
    private javax.swing.JTextField returnIndexget;
    private javax.swing.JTextField returnNameget;
    // End of variables declaration//GEN-END:variables
}
