/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Novella.YMain;

//import Novella.JFrames.*;

/**
 *
 * @author Koka
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hidebar1 = new javax.swing.JPanel();
        Hidebar3 = new javax.swing.JPanel();
        Hidebar4 = new javax.swing.JPanel();
        Hidebar2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        IssueBookjPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RecievejPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        AddNewBookJPanel = new javax.swing.JPanel();
        AddNewStudentJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        AddNewStudent = new javax.swing.JLabel();
        IssueBook1 = new javax.swing.JLabel();
        AddNewBook = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hidebar1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar1Layout = new javax.swing.GroupLayout(Hidebar1);
        Hidebar1.setLayout(Hidebar1Layout);
        Hidebar1Layout.setHorizontalGroup(
            Hidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Hidebar1Layout.setVerticalGroup(
            Hidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 20, 420));

        Hidebar3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar3Layout = new javax.swing.GroupLayout(Hidebar3);
        Hidebar3.setLayout(Hidebar3Layout);
        Hidebar3Layout.setHorizontalGroup(
            Hidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        Hidebar3Layout.setVerticalGroup(
            Hidebar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 740, 30));

        Hidebar4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar4Layout = new javax.swing.GroupLayout(Hidebar4);
        Hidebar4.setLayout(Hidebar4Layout);
        Hidebar4Layout.setHorizontalGroup(
            Hidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        Hidebar4Layout.setVerticalGroup(
            Hidebar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, 20));

        Hidebar2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Hidebar2Layout = new javax.swing.GroupLayout(Hidebar2);
        Hidebar2.setLayout(Hidebar2Layout);
        Hidebar2Layout.setHorizontalGroup(
            Hidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Hidebar2Layout.setVerticalGroup(
            Hidebar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(Hidebar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 20, 420));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        IssueBookjPanel.setBackground(new java.awt.Color(255, 255, 255));
        IssueBookjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Issue Book");
        IssueBookjPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jTabbedPane1.addTab("tab1", IssueBookjPanel);

        RecievejPanel.setBackground(new java.awt.Color(255, 255, 255));
        RecievejPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", RecievejPanel);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel5);

        AddNewBookJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AddNewBookJPanelLayout = new javax.swing.GroupLayout(AddNewBookJPanel);
        AddNewBookJPanel.setLayout(AddNewBookJPanelLayout);
        AddNewBookJPanelLayout.setHorizontalGroup(
            AddNewBookJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        AddNewBookJPanelLayout.setVerticalGroup(
            AddNewBookJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", AddNewBookJPanel);

        AddNewStudentJPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddNewStudentJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Add New Student");
        AddNewStudentJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Student Novella ID:");
        AddNewStudentJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Student Name:");
        AddNewStudentJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Student Class:");
        AddNewStudentJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Student Index:");
        AddNewStudentJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Student Address:");
        AddNewStudentJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Student Phone:");
        AddNewStudentJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        AddNewStudentJPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        AddNewStudentJPanel.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 0, 0));
        AddNewStudentJPanel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, -1));

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 0, 0));
        AddNewStudentJPanel.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, -1));

        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 0, 0));
        AddNewStudentJPanel.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Student Island:");
        AddNewStudentJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 0));
        AddNewStudentJPanel.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Save");
        jButton1.setToolTipText("");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        AddNewStudentJPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 20));

        jButton2.setText("jButton2");
        AddNewStudentJPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(0, 0, 0));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        AddNewStudentJPanel.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 180, -1));

        jTabbedPane1.addTab("tab6", AddNewStudentJPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 740, 420));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 170, 10));

        AddNewStudent.setBackground(new java.awt.Color(255, 255, 255));
        AddNewStudent.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AddNewStudent.setForeground(new java.awt.Color(255, 255, 255));
        AddNewStudent.setText("Sudent Directory");
        AddNewStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddNewStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddNewStudentMouseExited(evt);
            }
        });
        getContentPane().add(AddNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        IssueBook1.setBackground(new java.awt.Color(255, 255, 255));
        IssueBook1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        IssueBook1.setForeground(new java.awt.Color(255, 255, 255));
        IssueBook1.setText("Issue Book");
        IssueBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueBook1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IssueBook1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IssueBook1MouseExited(evt);
            }
        });
        getContentPane().add(IssueBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        AddNewBook.setBackground(new java.awt.Color(255, 255, 255));
        AddNewBook.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AddNewBook.setForeground(new java.awt.Color(255, 255, 255));
        AddNewBook.setText("Add New Book");
        AddNewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddNewBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddNewBookMouseExited(evt);
            }
        });
        getContentPane().add(AddNewBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Novella/YMain/Images/AA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        setSize(new java.awt.Dimension(996, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewStudentMouseEntered
        // TODO add your handling code here:
        AddNewStudent.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_AddNewStudentMouseEntered

    private void AddNewStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewStudentMouseExited
        // TODO add your handling code here:
        AddNewStudent.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_AddNewStudentMouseExited

    private void IssueBook1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook1MouseEntered
        // TODO add your handling code here:
        IssueBook1.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_IssueBook1MouseEntered

    private void IssueBook1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook1MouseExited
        // TODO add your handling code here:
        IssueBook1.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_IssueBook1MouseExited

    private void AddNewBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewBookMouseEntered
        // TODO add your handling code here:
        AddNewBook.setForeground(new java.awt.Color (183,227,234));
    }//GEN-LAST:event_AddNewBookMouseEntered

    private void AddNewBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewBookMouseExited
        // TODO add your handling code here:
        AddNewBook.setForeground(new java.awt.Color (255,255,255));
    }//GEN-LAST:event_AddNewBookMouseExited

    private void AddNewBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewBookMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(AddNewBookJPanel);
    }//GEN-LAST:event_AddNewBookMouseClicked

    private void AddNewStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewStudentMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(AddNewStudentJPanel);
    }//GEN-LAST:event_AddNewStudentMouseClicked

    private void IssueBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBook1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(IssueBookjPanel);
    }//GEN-LAST:event_IssueBook1MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewBook;
    private javax.swing.JPanel AddNewBookJPanel;
    private javax.swing.JLabel AddNewStudent;
    private javax.swing.JPanel AddNewStudentJPanel;
    private javax.swing.JPanel Hidebar1;
    private javax.swing.JPanel Hidebar2;
    private javax.swing.JPanel Hidebar3;
    private javax.swing.JPanel Hidebar4;
    private javax.swing.JLabel IssueBook1;
    private javax.swing.JPanel IssueBookjPanel;
    private javax.swing.JPanel RecievejPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
